### ISSUE TITLE
proguard-rules 

### ISSUE THREAD

**Issue by ernestkamara** [blipinsk/ViewPropertyObjectAnimator#10]
Hi,
I am using https://github.com/arimorty/floatingsearchview which uses your library and seems to be lacking proguard rules for your library.
I have already open an [issue](https://github.com/arimorty/floatingsearchview/issues/45), but want to know if you have any pre-define proguard-rules when using your ViewPropertyObjectAnimator library?

Thanks.
Stacktrace:
`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bartoszlipinski/viewpropertyobjectanimator/ViewPropertyObjectAnimator;
        at com.arlib.floatingsearchview.FloatingSearchView.transitionInLeftSection(FloatingSearchView.java:1406)
        at com.arlib.floatingsearchview.FloatingSearchView.setSearchFocusedInternal(FloatingSearchView.java:1319)
        at com.arlib.floatingsearchview.FloatingSearchView.access$1500(FloatingSearchView.java:87)
        at com.arlib.floatingsearchview.FloatingSearchView$7.onFocusChange(FloatingSearchView.java:609)
        at android.view.View.onFocusChanged(View.java:5723)
        at android.widget.TextView.onFocusChanged(TextView.java:8224)
        at android.view.View.handleFocusGainInternal(View.java:5478)
        at android.view.View.requestFocusNoSearch(View.java:8476)
        at android.view.View.requestFocus(View.java:8455)
        at android.view.View.requestFocus(View.java:8422)
        at android.view.View.requestFocus(View.java:8401)
        at android.view.View.onTouchEvent(View.java:10305)
        at android.widget.TextView.onTouchEvent(TextView.java:8300)
        at android.view.View.dispatchTouchEvent(View.java:9300)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
        at android.view.View.dispatchPointerEvent(View.java:9520)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4104)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3852)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5932)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5906)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5867)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6035)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5422)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bartoszlipinski.viewpropertyobjectanimator.ViewProp
                            ertyObjectAnimator" on path: DexPathList[[zip file "/data/app/net.zedge.snakk-2/base.apk"],nativeLibraryDirectories=[/d
                            ata/app/net.zedge.snakk-2/lib/arm64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        ... 71 more
        Suppressed: java.lang.ClassNotFoundException: com.bartoszlipinski.viewpropertyobjectanimator.ViewPropertyObjectAnim
                            ator
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 72 more
        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
            FlurryAgent  W  Error logged: uncaught
    Flurry session ended`

**Comment by blipinsk** [comment]
Hi, thanks for the issue.
I don't really use proguard myself, so I don't think I'm currently capable of writing those rules. Do you know proguard thoroughly?

**Comment by ernestkamara** [comment]
I do know some basic Proguard config and would send a PR when i have time.

**Comment by blipinsk** [comment]
👍

**Comment by Zhuinden** [comment]
I just threw 
```
#view property object animator
-keep class com.bartoszlipinski.viewpropertyobjectanimator.** { *; }` 
```

at it to make sure.

**Comment by blipinsk** [comment]
alright, I take your word on that @Zhuinden. Can you add proguard section to README.md (and send a PR)?

**Comment by Zhuinden** [comment]
Well technically it just keeps every class in `viewpropertyobjectanimator` so I didn't need to think about it 😄  there can be smarter ways to do it
